version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-banking-app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - go-banking-network

  postgres:
    image: postgres:16.4
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    networks:
      - go-banking-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      timeout: 45s
      interval: 10s
      retries: 10

networks:
  go-banking-network:
    driver: bridge
