// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	Balance    float64            `json:"balance"`
	Currency   string             `json:"currency"`
	Status     string             `json:"status"`
	InsertedAt pgtype.Timestamptz `json:"inserted_at"`
}

type Transaction struct {
	ID         string             `json:"id"`
	AccountID  int64              `json:"account_id"`
	Amount     float64            `json:"amount"`
	Source     string             `json:"source"`
	Type       string             `json:"type"`
	InsertedAt pgtype.Timestamptz `json:"inserted_at"`
}

type User struct {
	ID         int64              `json:"id"`
	Username   string             `json:"username"`
	FullName   string             `json:"full_name"`
	Email      string             `json:"email"`
	InsertedAt pgtype.Timestamptz `json:"inserted_at"`
}
